"""refactor user model types

Revision ID: c003f16a33d9
Revises: 4bd7a67f45fd
Create Date: 2025-12-26 15:10:49.818297

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c003f16a33d9"
down_revision: Union[str, Sequence[str], None] = "4bd7a67f45fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
